In [1]:
import numpy as np
from sight_line_constructor import Sightline
import read_cubes
from scipy import ndimage
import matplotlib.pyplot as plt


In [2]:
path = "/var/lib/libvirt/images/nbody/baorsd/run101/density_field/S020_CIC1024_conf.bin"

cube = read_cubes.read(path)

In [3]:
res = 2
start_point = np.array([0,0,0]) #Mpc/h
end_point = np.array([300,300,500]) #Mpc/h


In [4]:
s1 = Sightline(start_point,end_point,num=3000)

In [5]:
los_dens = s1.calc_los(res,cube)

In [25]:
end_points = np.random.uniform(-2,2,(5,3))

In [26]:
for i in end_points:
    print (i)

[-1.61706498  0.20630828 -1.22517578]
[-1.40833365  0.00624378  1.60157729]
[-1.74232014 -0.35255102 -1.15300227]
[-0.71738662  1.49207374  1.38073353]
[ 0.06184101 -0.69498059 -0.21844667]
